.github/workflows/review.yaml, src/pages/Home/index.tsx
CI上のlintが厳密に効いていなかったのを修正
CIが動いていれば問題なし
=> CVS-164 CI上のlintを厳密に適用する

package.json, yarn.lock
aspidaをプロジェクトの依存に含めた
特にチェックする内容はなし
=> CVS-165 aspidaを依存に含める

.eslintrc.js, .prettierignore, .storybook/main.js, .storybook/main.ts, .storybook/preview.jsx, .storybook/public/mockServiceWorker.js, package.json, src/components/organisms/Cards/InstanceCards/HostStatusCard.stories.tsx, src/lib/msw/browser.ts, src/lib/msw/handlerFactory.ts, src/lib/msw/handlers.ts, src/lib/msw/server.ts, src/pages/Home/index.tsx, vitest.setup.ts, yarn.lock
Storybookとテスト用のmockを整備した
storybookの表示を確認
=> CVS-181 mswのセットアップ

.github/workflows/review.yaml, .github/workflows/storybook.yaml
=> CVS-182 storybookをgithub pagesにデプロイする

.storybook/main.ts, package.json, yarn.lock
=> CVS-182 Github Pagesにassetsを含める

.github/workflows/code-test.yaml, README.md, package.json, vite.config.ts, yarn.lock
=> CVS-183 codecovを使う

.storybook/preview.jsx, package.json
=> CVS-182 github pagesでstorybookが壊れるのを直す

.storybook/preview.jsx, package.json
=> CVS-182 mswのパスを修正

.storybook/preview.jsx
=> CVS-182 ローカルでstorybookが動かないのを修正

.github/workflows/cd.yaml, package.json
=> CVS-208 git-hooksの修正

.github/workflows/cd.yaml
=> CVS-200 self-hosted runner から github に runner の実行環境を移行

.github/workflows/cd.yaml
アクションの使い方間違えていたので
merge して動作テスト
=> CVS-200 ワークフローの修正

.github/workflows/cd.yaml, .github/workflows/code-test.yaml, .github/workflows/review.yaml, .github/workflows/storybook.yaml
https://github.com/actions/cache/blob/main/examples.md#node---npm
=> CVS-209 github actionsの記法を変更

.github/workflows/deploy-prd.yaml, .github/workflows/deploy-stg.yaml
production 環境へデプロイする GitHub Actions のワークフローを作成した
Action を実行してデプロイされるか確認。
Production 環境にブラウザからアクセスし、正しくウェブページが表示されていることを確認した。
=> CVS-211 prd 環境へのデプロイを作成

renovate.json
=> CVS-213 renovate enable automerge

package.json, vite.config.ts, yarn.lock
https://github.com/capricorn86/happy-dom/issues/494#issuecomment-1341494509
=> CVS-217 jsdomをhappy-domに戻す

renovate.json
=> CVS-213 RenovateでGitHubのautomergeを使う

.github/workflows/deploy-prd.yaml, .github/workflows/deploy-stg.yaml
デプロイワークフローの rsync deployments のところで停止しているのを修正
```
client_loop: send disconnect: Broken pipe
rsync: connection unexpectedly closed (23544 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(***8) [sender=3.2.4]
```
=> CVS-229 ワークフローの修正

.github/workflows/storybook.yaml, src/components/molecules/Charts/Bar/BarChart.stories.tsx, src/components/organisms/Cards/InstanceCards/HostMemoryCard.stories.tsx, src/components/organisms/Cards/InstanceCards/RunningVmsCard.stories.tsx
=> CVS-226 find-commentを修正

.github/workflows/code-test.yaml, .github/workflows/review.yaml, .github/workflows/storybook.yaml, renovate.json, src/components/molecules/Charts/Bar/BarChart.stories.tsx, src/components/molecules/Charts/Doughnut/DoughnutChart.stories.tsx, src/components/organisms/Cards/InstanceCards/HostMemoryCard.stories.tsx, src/components/organisms/Cards/InstanceCards/RunningVmsCard.stories.tsx
=> CVS-226 storybookのdelayを増やす

.github/workflows/reg-suit.yaml, package.json, regconfig.json, src/components/molecules/Charts/Bar/BarChart.stories.tsx, yarn.lock
パッケージ名typoしてたりreg-suitが実は動いてなかったりしたのを修正
=> CVS-226 もろもろ修正

package.json, regconfig.json
=> CVS-226 reg-suitの許容誤差を変更

.github/workflows/reg-suit.yaml
=> CVS-226 mainでCIが落ちるのを修正

.storybook/main.ts, .storybook/preview.jsx, package.json, squoosh.ts, src/components/molecules/Charts/Bar/BarChart.stories.tsx, src/components/molecules/Charts/Doughnut/DoughnutChart.stories.tsx, src/components/organisms/Cards/InstanceCards/HostMemoryCard.stories.tsx, src/components/organisms/Cards/InstanceCards/HostStatusCard.stories.tsx, src/components/organisms/Cards/InstanceCards/RunningVmsCard.stories.tsx, yarn.lock
=> CVS-226 storycapの設定を調整

src/components/molecules/Charts/Doughnut/DoughnutChart.stories.tsx, src/components/organisms/Cards/InstanceCards/HostMemoryCard.stories.tsx, src/components/organisms/Cards/InstanceCards/HostStatusCard.stories.tsx, src/components/organisms/Cards/InstanceCards/RunningVmsCard.stories.tsx
~~GitHub Actionsのrunner貧弱すぎてキレそう~~
=> CVS-226 storycapのdelayを増やす

.github/workflows/reg-suit.yaml
=> CVS-226 actionsにworkaroundを追加

.storybook/preview.jsx, package.json, src/components/organisms/Cards/InstanceCards/HostStatusCard.tsx, src/components/organisms/Cards/InstanceCards/RunningVmsCard.tsx, src/components/organisms/Tables/InstanceTable/InstanceTable.tsx, src/pages/VNC/VNC.tsx, src/pages/VNC/index.ts, src/utils/Routing.tsx, yarn.lock
=> CVS-233 Add VNC Console

src/components/molecules/Charts/Bar/BarChart.stories.tsx, src/components/molecules/Charts/Doughnut/DoughnutChart.stories.tsx
=> CVS-235 VRTの挙動を修正

src/components/organisms/Dialogs/EditVmDialog/EditVmDialog.tsx, src/components/organisms/Forms/UpdateVm/UpdateVmForm.spec.tsx, src/components/organisms/Forms/UpdateVm/UpdateVmForm.stories.tsx, src/components/organisms/Forms/UpdateVm/UpdateVmForm.tsx
=> CVS-241 実装時の考慮漏れを修正

src/components/organisms/Drawers/SideBar/SideBar.tsx, src/templates/DashBoard/DashBoard.tsx
=> CVS-255 サイドバーの表示不具合を修正

.github/workflows/code-test.yaml, src/components/organisms/Dialogs/CreateVmDialog/CreateVmDialog.tsx, src/components/organisms/Dialogs/DialogWithAtoms/Dialog.tsx, src/components/organisms/Dialogs/EditVmDialog/atoms.ts, src/components/organisms/Dialogs/Error/ErrorDialog.tsx, src/components/organisms/Menu/VMControlMenu/atoms.ts, src/components/organisms/Tabs/InstanceTabs/InstanceTabs.tsx, src/components/organisms/Tabs/TabsWithAtoms/Tabs.stories.tsx, src/components/organisms/Tabs/TabsWithAtoms/Tabs.tsx
=> CVS-259 fix types

.github/workflows/deploy-prd.yaml, .github/workflows/deploy-stg.yaml
=> CVS-260 add envvar in deploy workflow

README.md
=> CVS-262 README の充実
